server:
  host: "0.0.0.0"
  port: "8080"

kafka:
  bootstrap_servers: "kafka:9092"
  topic: "push-notifications"
  group_id: "notification-consumer-group"
  auto_offset_reset: "earliest"

redis:
  host: "redis"
  port: "6379"
  password: ""
  db: 0

log:
  level: "info"
  file: ""